name: example
on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  schedule:
    - cron: "50 15 * * 2"
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "GitHub Event: ${GITHUB_EVENT_NAME}"
          echo "GitHub Repository: ${GITHUB_REPOSITORY}"
          echo "GitHub Event Pull Request Merged: ${GITHUB_EVENT_PULL_REQUEST_MERGED}"
          echo "GitHub Ref: ${GITHUB_REF}"
